### PR TITLE
* allow picking from all KeyCodes in the key binding UI.

### PR DESCRIPTION
**Pull request by kspdrgn**
Adds more KeyCodes to Config UI.

Now supports Dvorak!

Tested in ksp 1.10.1

ksp wsad camera keys mod

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Oh, I wasn't aware of this.  I'll review in my next batch of updates
Thank you

**Comment by linuxgurugamer** [comment]
Thank you

**Comment by linuxgurugamer** [comment]
I had to revert this change, it wasn't working and was locking up the keyboard

**Comment by linuxgurugamer** [comment]
I'll be redoing this, problem was in my build server

**Comment by kspdrgn** [comment]
Thanks :)

**Pull request merged**
